name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 0 * * 1' # runs weekly on Mondays
  workflow_dispatch: {}

permissions: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo sync "$GITHUB_REPOSITORY" -b main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
