# Source - https://stackoverflow.com/a/76432467
# Posted by DearVolt
# Retrieved 2026-05-21, License - CC BY-SA 4.0

name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write # required since we are updating workflow files
    steps:
      - run: gh repo sync "$GITHUB_REPOSITORY" -b main
        env:
          GH_TOKEN: ${{ github.token }}

